In [2]:
import numpy as np
import cv2

# Load an color image in grayscale
img = cv2.imread('resources/basic_object/cube.jpg',1)
img = cv2.flip(img, 0)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
A = [1, 2, 4]

In [4]:
tvec = np.array([[3],[2],[1]])

In [5]:
tvec.shape

(3, 1)

In [6]:
tvec[1]

array([2])

In [7]:
tvec.shape = (3,)

In [8]:
tvec

array([3, 2, 1])

In [10]:
A = np.array([-154.10873304,  171.43085636, -778.16465736])

In [11]:
-778/3

-259.3333333333333

In [12]:
A / 260.0

array([-0.5927259 ,  0.65934945, -2.99294099])